using Builder.Instantiation;
using Builder.Declaration;
using SyntaxTree;
using TypeModel.Symbols;
using TypeModel.Types;

namespace Builder.Desugaring.Passes;

/// <summary>
/// Lowers <see cref="GenericMemberRoutineCallExpression"/> nodes to plain <see cref="CallExpression"/>
/// nodes where possible. Runs after <see cref="Builder.Lowering.Passes.ExpressionLoweringPass"/> in the per-file pipeline.
///
/// <para>Lowered cases (require <c>ResolvedRoutine != null</c> from Phase 4):</para>
/// <list type="bullet">
/// <item><b>Type constructor with resolved <c>create</c></b>:
/// <c>Maybe[S64](value: x)</c> -> <c>CallExpression(IdentifierExpression("create"), args)</c></item>
/// <item><b>Generic memberRoutine call on receiver</b>:
/// <c>buf.read![U8](offset)</c> ??
/// <c>CallExpression(MemberExpression(buf, "read!"), args, TypeArguments=[U8])</c></item>
/// </list>
///
/// <para>Kept as <see cref="GenericMemberRoutineCallExpression"/> (not lowered):</para>
/// <list type="bullet">
/// <item>Collection literals -> <c>IsCollectionLiteral == true</c>;
/// codegen emits <c>create + add_last</c> loops.</item>
/// <item>Unresolved calls -> <c>ResolvedRoutine == null</c> and no safe lowering target
/// has been determined yet.</item>
/// </list>
/// </summary>
internal sealed class GenericCallLoweringPass : AstRewriter
{
    /// <summary>
    /// Stores the registry state used by this compiler phase.
    /// </summary>
    private readonly TypeRegistry _registry;

    private readonly Dictionary<string, Statement> _variantBodies;
    private readonly Dictionary<string, MonomorphizedBody>? _instantiatedGenericBodies;

    /// <summary>Warm-restore stdlib variant keys already lowered at snapshot capture — skipped by
    /// <see cref="RunOnVariantBodies"/>. Empty on cold builds and non-desugaring-context callers.</summary>
    private readonly HashSet<string> _restoredVariantKeys;

    /// <summary>
    /// Initializes a new instance with the dependencies required for its compiler phase.
    /// </summary>
    public GenericCallLoweringPass(DesugaringContext ctx) : this(registry: ctx.Registry,
        variantBodies: ctx.VariantBodies,
        instantiatedGenericBodies: ctx.InstantiatedGenericBodies,
        restoredVariantKeys: ctx.RestoredVariantKeys)
    {
    }

    /// <summary>
    /// Initializes a new instance with the dependencies required for its compiler phase.
    /// </summary>
    public GenericCallLoweringPass(TypeRegistry registry,
        Dictionary<string, Statement> variantBodies) : this(registry: registry,
        variantBodies: variantBodies,
        instantiatedGenericBodies: null)
    {
    }

    /// <summary>
    /// Initializes a new instance with the dependencies required for its compiler phase.
    /// </summary>
    private GenericCallLoweringPass(TypeRegistry registry,
        Dictionary<string, Statement> variantBodies,
        Dictionary<string, MonomorphizedBody>? instantiatedGenericBodies,
        HashSet<string>? restoredVariantKeys = null)
    {
        _registry = registry;
        _variantBodies = variantBodies;
        _instantiatedGenericBodies = instantiatedGenericBodies;
        _restoredVariantKeys = restoredVariantKeys ??
                               new HashSet<string>(comparer: StringComparer.Ordinal);
    }

    /// <summary>
    /// Runs this compiler phase over its configured input.
    /// </summary>
    public void Run(Program program)
    {
        for (int i = 0; i < program.Declarations.Count; i++)
        {
            switch (program.Declarations[index: i])
            {
                case RoutineDeclaration r:
                {
                    Statement newBody = VisitStatement(stmt: r.Body);
                    if (!ReferenceEquals(objA: newBody, objB: r.Body))
                    {
                        program.Declarations[index: i] = r with { Body = newBody };
                    }

                    break;
                }

                case EntityDeclaration e:
                    LowerMemberList(members: e.Members);
                    break;

                case RecordDeclaration rec:
                    LowerMemberList(members: rec.Members);
                    break;

                case CrashableDeclaration cr:
                    LowerMemberList(members: cr.Members);
                    break;
            }
        }
    }

    /// <summary>
    /// Lowers GMCEs in all variant bodies generated by ErrorHandlingVariantPass.
    /// Must run after SA so that ResolvedRoutine is set on GMCEs that SA resolved.
    /// </summary>
    public void RunOnVariantBodies()
    {
        foreach (string key in _variantBodies.Keys.ToList())
        {
            if (_restoredVariantKeys.Contains(item: key))
            {
                continue; // already lowered at snapshot capture
            }

            Statement body = _variantBodies[key: key];
            Statement lowered = VisitStatement(stmt: body);
            if (!ReferenceEquals(objA: lowered, objB: body))
            {
                _variantBodies[key: key] = lowered;
            }
        }
    }

    /// <summary>
    /// Lowers GMCEs in all instantiated generic bodies produced during Phase 7.
    /// These bodies must meet the same backend-entry contract as ordinary programs.
    /// </summary>
    public void RunOnInstantiatedGenericBodies()
    {
        if (_instantiatedGenericBodies == null)
        {
            return;
        }

        RunOnInstantiatedGenericBodies(bodies: _instantiatedGenericBodies);
    }

    /// <summary>
    /// Lowers GMCEs in the GIVEN body map. The warm-restore closure passes a SEPARATE <c>freshBodies</c>
    /// dict (the NEW bodies GMP built this run); the sibling per-body lowering passes (f-string/operator/
    /// …) mutate that same dict and it is merged back into the shared instantiation map afterwards. Running
    /// this pass on the shared map instead would strand its lowered fresh bodies — the merge-back would
    /// overwrite them with the un-GMCE-lowered <c>freshBodies</c> copies (the warm-only GMCE-survives bug).
    /// Cold passes the shared map itself (freshBodies IS the map), so the behavior is unchanged there.
    /// </summary>
    public void RunOnInstantiatedGenericBodies(Dictionary<string, MonomorphizedBody> bodies)
    {
        foreach (string key in bodies.Keys.ToList())
        {
            MonomorphizedBody body = bodies[key: key];
            // NOTE: Previously skipped synthesized bodies (assumed they never contained GMCEs),
            // but wrapper represent/diagnose forwarders synthesized by WiredRoutinePass /
            // wrapper-forwarder synthesis DO contain GMCEs (e.g. Hijacked[T].x calls). Lower
            // them too so they meet the codegen contract.
            Statement lowered = VisitStatement(stmt: body.Ast.Body);
            if (!ReferenceEquals(objA: lowered, objB: body.Ast.Body))
            {
                bodies[key: key] = body with { Ast = body.Ast with { Body = lowered } };
            }
        }
    }

    /// <summary>
    /// Lower member list as part of this compiler phase.
    /// </summary>
    private void LowerMemberList(List<SyntaxTree.Declaration> members)
    {
        for (int j = 0; j < members.Count; j++)
        {
            if (members[index: j] is not RoutineDeclaration m)
            {
                continue;
            }

            Statement newBody = VisitStatement(stmt: m.Body);
            if (!ReferenceEquals(objA: newBody, objB: m.Body))
            {
                members[index: j] = m with { Body = newBody };
            }
        }
    }

    // -----------------------------------------------------------------------------

    /// <summary>
    /// The core transform: lower a <see cref="GenericMemberRoutineCallExpression"/> to a plain
    /// <see cref="CallExpression"/> / <see cref="CreatorExpression"/> where possible, else fall
    /// through to just rewriting its children. All other structural recursion comes from
    /// <see cref="AstRewriter"/>.
    /// </summary>
    protected override Expression VisitGenericMemberRoutineCall(
        GenericMemberRoutineCallExpression e)
    {
        return TryLowerGenericCall(gmc: e) ?? LowerGenericCallChildren(gmc: e);
    }

    /// <summary>
    /// Rewrites children, then re-copies the mutable resolution metadata that <c>with</c> drops.
    /// </summary>
    protected override Expression VisitCall(CallExpression e)
    {
        Expression rebuilt = base.VisitCall(e: e);
        if (ReferenceEquals(objA: rebuilt, objB: e) || rebuilt is not CallExpression rewritten)
        {
            return rebuilt;
        }

        // ResolvedRoutine/ResolvedType/etc. are mutable {get;set;} props — `with` drops them.
        rewritten.ResolvedRoutine = e.ResolvedRoutine;
        rewritten.LoweringKind = e.LoweringKind;
        rewritten.ConstructedType = e.ConstructedType;
        rewritten.IsCollectionLiteral = e.IsCollectionLiteral;
        rewritten.TypeArguments = e.TypeArguments;
        rewritten.ResolvedType = e.ResolvedType;
        return rewritten;
    }

    /// <summary>
    /// Rewrites the receiver, then re-copies <c>ResolvedType</c> that <c>with</c> drops.
    /// </summary>
    protected override Expression VisitMember(MemberExpression e)
    {
        Expression rebuilt = base.VisitMember(e: e);
        if (ReferenceEquals(objA: rebuilt, objB: e) || rebuilt is not MemberExpression rewritten)
        {
            return rebuilt;
        }

        rewritten.ResolvedType = e.ResolvedType;
        return rewritten;
    }

    /// <summary>
    /// Rewrites the member values, then re-copies the mutable resolution metadata that <c>with</c>
    /// drops. Constructor arguments can themselves be GMCEs (e.g. <c>Limbs[4](d: Array[U32, 4]())</c>).
    /// </summary>
    protected override Expression VisitCreator(CreatorExpression e)
    {
        Expression rebuilt = base.VisitCreator(e: e);
        if (ReferenceEquals(objA: rebuilt, objB: e) || rebuilt is not CreatorExpression rewritten)
        {
            return rebuilt;
        }

        // Mutable {get;set;} props are dropped by `with` — carry them over.
        rewritten.LoweringKind = e.LoweringKind;
        rewritten.ConstructedType = e.ConstructedType;
        rewritten.ResolvedCreatorRoutine = e.ResolvedCreatorRoutine;
        rewritten.ResolvedType = e.ResolvedType;
        return rewritten;
    }

    /// <summary>
    /// Returns true when <paramref name="type"/> is a record/entity with no member variables —
    /// so a zero-arg <see cref="CreatorExpression"/> over it is structurally valid (a bare
    /// zero-init of the type's storage). Returns false for null and for types that carry
    /// fields needing initialization.
    /// </summary>
    private static bool HasZeroMemberVariables(TypeSymbol? type)
    {
        return type switch
        {
            RecordTypeSymbol r => r.MemberVariables.Count == 0,
            EntityTypeSymbol e => e.MemberVariables.Count == 0,
            _ => false
        };
    }

    /// <summary>
    /// Resolves the constructed type for a construction GMCE (<c>List[S64]()</c>): the SA-stamped
    /// <see cref="GenericMemberRoutineCallExpression.ConstructedType"/> when present, else the type named by
    /// <see cref="GenericMemberRoutineCallExpression.MemberRoutineName"/> specialized by its explicit type
    /// args (a generic def + matching arg count → the concrete instance). Returns null when the name is not a
    /// type or an arg doesn't resolve. Used to bind a no-arg creator for a cold-path monomorphized body.
    /// </summary>
    private TypeSymbol? ResolveConstructionTypeForGmc(GenericMemberRoutineCallExpression gmc)
    {
        if (gmc.ConstructedType is { } ct and not ErrorTypeSymbol)
        {
            return ct;
        }

        // Prefer the import-aware short-name lookup; on a cold-materialized stdlib body the constructing
        // type (`WhereIterable`) lives in another module (IterTools) and is NOT in this pass's ambient
        // import scope, so the short-name lookup honestly fails. Fall back to a scan for the matching
        // generic DEFINITION by bare name — the type args below still fully pin the concrete instance.
        TypeSymbol? baseType = _registry.LookupType(name: gmc.MemberRoutineName)
                               ?? _registry.GetAllTypes().FirstOrDefault(predicate: t =>
                                   t.IsGenericDefinition && t.BareName == gmc.MemberRoutineName);
        if (baseType is null)
        {
            return null;
        }

        if (!baseType.IsGenericDefinition)
        {
            return baseType;
        }

        if (baseType.GenericParameters?.Count != gmc.TypeArguments.Count)
        {
            return null;
        }

        var args = new List<TypeSymbol>(capacity: gmc.TypeArguments.Count);
        foreach (TypeExpression te in gmc.TypeArguments)
        {
            TypeSymbol? arg = te.ResolvedType is { } rt and not ErrorTypeSymbol
                ? rt
                : _registry.LookupType(name: te.Name);
            if (arg is null or ErrorTypeSymbol || ContainsGenericParam(t: arg))
            {
                return null;
            }

            args.Add(item: arg);
        }

        return _registry.GetOrCreateResolution(genericDef: baseType, typeArguments: args);
    }

    /// <summary>
    /// Tries to lower a <see cref="GenericMemberRoutineCallExpression"/> to a plain
    /// <see cref="CallExpression"/>. Returns <c>null</c> if the node cannot be safely lowered.
    /// </summary>
    private Expression? TryLowerGenericCall(GenericMemberRoutineCallExpression gmc)
    {
        // Collection literals need special codegen (create + add_last loop).
        if (gmc.IsCollectionLiteral)
        {
            return null;
        }

        // A construction GMC (`WhereIterable[T, Me](...)`) monomorphized on the COLD path carries concrete
        // TypeArguments but a NULL ConstructedType: it's re-materialized from an un-SA'd stdlib template, and
        // the `with`-clone in monomorphization drops the mutable ConstructedType stamp SA would have set. Recover
        // it from MemberRoutineName + the concrete TypeArguments so the field-init guard below fires (it keys on
        // ConstructedType). Without this the GMC survives to codegen and trips the residual-node check. On the
        // warm path ConstructedType is already set, so this is a no-op.
        if (gmc.ConstructedType is null && !gmc.IsMemoryOperation && gmc.ResolvedRoutine == null &&
            gmc.Object is IdentifierExpression ctId && ctId.Name == gmc.MemberRoutineName &&
            ResolveConstructionTypeForGmc(gmc: gmc) is { IsGenericDefinition: false } recovered)
        {
            // ConstructedType is a mutable {get;set;} prop — set it in place (a `with` clone would drop it).
            gmc.ConstructedType = recovered;
        }

        // -----------------------------------------------------------------------------
        // SA finds no matching create overload (e.g. List[T](data:..., count:..., capacity:...))
        // because this is a raw field-initialization form, not a regular routine call.
        // Lower to CreatorExpression so codegen's EmitConstructorCall handles it.
        // Also covers zero-arg construction of zero-field records and const-generic record
        // resolutions (e.g. BitArray[8](), Array[S64, 4]()) — SA marks these as type
        // constructions via ConstructedType/LoweringKind=TypeConstructor but never finds a
        // matching create() to bind ResolvedRoutine. Without lowering they'd survive as
        // GMCEs and trip the IllegalBackendResidualNode check.
        //
        // Zero-arg construction of a type that has fields (e.g. CircularList[S64]()) is NOT lowered
        // here — the type relies on a real create() overload that SA failed to bind, and
        // forging an empty CreatorExpression would just re-issue the bug as S455
        // (missing field). Leave that case to the SA fix path.
        // A FAILABLE construction `Type![Args](args)` (IsMemoryOperation) must NOT be lowered to a
        // field-init CreatorExpression here — it routes to the type's failable `create!` overload
        // (e.g. the variant-arm extractor `Dict[Text, SerialValue].create!(from: sv)`). Leave it as a
        // GMC so SA resolves the creator; SA-time lowering (below, once ResolvedRoutine is set) or the
        // creator-routing path handles it.
        if (gmc.Object is IdentifierExpression literalId &&
            literalId.Name == gmc.MemberRoutineName && !gmc.IsMemoryOperation &&
            gmc.ResolvedRoutine == null
            // Constructor form `Type[Args](...)`: MemberRoutineName names a type. Prefer the SA-resolved
            // ConstructedType (import-precise) over a bare `LookupType(name)`, which only found a
            // cross-module type (e.g. Collections.BitArray) via the short-name scan.
            && (gmc.ConstructedType != null ||
                _registry.LookupType(name: gmc.MemberRoutineName) != null) &&
            (gmc.Arguments.Count > 0 || HasZeroMemberVariables(type: gmc.ConstructedType)))
        {
            return LowerFieldInitCreator(gmc: gmc);
        }

        // A zero-arg construction of a type WITH fields whose creator SA never bound — the cold-path
        // monomorphized protocol-default case: `Iterable[T].List()`'s body `var result = List[T]()`,
        // monomorphized to `List[S64]()`, reaches here (a fresh cold build re-materializes the body but
        // never re-SA's it, so `List[S64]()`'s ResolvedRoutine is null). The field-init lowering above skips
        // it (List has fields), and the null-return below would leave the GMCE for codegen to reject. `List`
        // HAS a real no-arg creator (`routine List[T]()`), so resolve it by signature and fall through to the
        // construction lowering — the same target SA would have bound on the warm/eager path.
        if (gmc.Object is IdentifierExpression ctorId && ctorId.Name == gmc.MemberRoutineName &&
            !gmc.IsMemoryOperation && gmc.ResolvedRoutine == null && gmc.Arguments.Count == 0 &&
            ResolveConstructionTypeForGmc(gmc: gmc) is { IsGenericDefinition: false } ctorType &&
            _registry.LookupCreatorOverload(type: ctorType, argTypes: []) is { } noArgCreator)
        {
            gmc = gmc with { ResolvedRoutine = noArgCreator, ConstructedType = ctorType };
        }

        // Only lower when SA has resolved the routine -> provides the concrete call target.
        if (gmc.ResolvedRoutine == null)
        {
            return null;
        }

        // A memberRoutine-generic call (`recast_as[T]`) whose ResolvedRoutine is still the generic-def
        // (its type param comes from the explicit `[T]` arg, so owner substitution alone can't
        // concretize it) must be re-instantiated from its now-concrete type arguments before it is
        // baked into a plain CallExpression — otherwise codegen receives a generic-def callee.
        gmc = gmc with { ResolvedRoutine = ConcretizeMemberRoutineGenericRoutine(gmc: gmc) };

        // Lower arguments first.
        var loweredArgs = new List<Expression>(capacity: gmc.Arguments.Count);
        foreach (Expression arg in gmc.Arguments)
        {
            loweredArgs.Add(item: VisitExpression(expr: arg));
        }

        // -----------------------------------------------------------------------------
        // e.g., Maybe[S64](present: true, value: x) -> SA resolved create and set ResolvedRoutine.
        // Also handles standalone generic free routines and LLVM intrinsic free functions where
        // Object.Name == memberRoutineName but there is no constructable type.
        // A failable generic construction `Type![Args](args)` parses with a BARE memberRoutineName equal to
        // the type name plus the structured IsMemoryOperation failable flag; treat it like the
        // construction case (same as `Type[Args](args)`) so its arguments are passed straight to the
        // resolved `create!` instead of being mis-lowered into a member call whose receiver (the type
        // name) becomes a null first argument.
        if (gmc.Object is IdentifierExpression id && id.Name == gmc.MemberRoutineName)
        {
            return LowerConstructionCall(gmc: gmc, id: id, loweredArgs: loweredArgs);
        }

        // -----------------------------------------------------------------------------
        // e.g., buf.read![U8](offset) -> CallExpression with TypeArguments=[U8].
        return LowerMemberRoutineCall(gmc: gmc, loweredArgs: loweredArgs);
    }

    /// <summary>
    /// Lowers a raw field-initialization / zero-arg construction GMC to a
    /// <see cref="CreatorExpression"/> so codegen's constructor path handles it.
    /// Returns null when the argument list mixes named and positional entries.
    /// </summary>
    private CreatorExpression? LowerFieldInitCreator(GenericMemberRoutineCallExpression gmc)
    {
        // Accept either fully named args (record-style field init) or fully positional
        // (constructor call form like Hijacked[T](me) from synthesized wrapper bodies).
        // CreatorExpression's MemberVariables uses ("", expr) for positional entries.
        bool allNamed = gmc.Arguments.All(predicate: a => a is NamedArgumentExpression);
        bool anyNamed = gmc.Arguments.Any(predicate: a => a is NamedArgumentExpression);
        if (!allNamed && anyNamed)
        {
            return null; // mixed named/positional — not our case
        }

        var members = new List<(string Name, Expression Value)>(capacity: gmc.Arguments.Count);
        foreach (Expression arg in gmc.Arguments)
        {
            if (arg is NamedArgumentExpression named)
            {
                members.Add(item: (named.Name, VisitExpression(expr: named.Value)));
            }
            else
            {
                members.Add(item: ("", VisitExpression(expr: arg)));
            }
        }

        return new CreatorExpression(TypeName: gmc.MemberRoutineName,
            TypeArguments: gmc.TypeArguments.Count > 0
                ? gmc.TypeArguments
                : null,
            MemberVariables: members,
            Location: gmc.Location)
        {
            LoweringKind = gmc.LoweringKind,
            ConstructedType = gmc.ConstructedType,
            ResolvedType = gmc.ResolvedType,
            IsInFlight = gmc.IsInFlight
        };
    }

    /// <summary>
    /// Lowers a resolved construction/free-routine GMC (<c>Object.Name == MemberRoutineName</c>) to a
    /// plain <see cref="CallExpression"/> whose callee names the type (constructions) or the resolved
    /// free routine.
    /// </summary>
    private static CallExpression LowerConstructionCall(GenericMemberRoutineCallExpression gmc,
        IdentifierExpression id, List<Expression> loweredArgs)
    {
        bool isTypeConstruction = gmc.ConstructedType != null ||
                                  gmc.LoweringKind is CallLoweringKind.TypeConstructor
                                      or CallLoweringKind.WrapperConstruction
                                      or CallLoweringKind.ValueConversion
                                      or CallLoweringKind.CollectionConstruction;
        return new CallExpression(
            // Callee is the type name (without the failable `!`); codegen constructs via
            // ConstructedType/ResolvedRoutine, so the name only identifies the type.
            Callee: new IdentifierExpression(Name: isTypeConstruction
                    ? id.Name
                    : gmc.ResolvedRoutine!.Name,
                Location: gmc.Location,
                // Preserve the `::` realm qualifier (`LLVM::add[U128]`) so a re-analysis of the
                // lowered body (monomorphized stdlib bodies re-run SA post-lowering) still sees the
                // foreign realm and the strict realm gate passes instead of false-flagging.
                Realm: id.Realm),
            Arguments: loweredArgs,
            Location: gmc.Location)
        {
            IsFailable = gmc.IsMemoryOperation,
            LoweringKind = gmc.LoweringKind,
            ConstructedType = gmc.ConstructedType,
            ResolvedRoutine = gmc.ResolvedRoutine,
            TypeArguments = gmc.TypeArguments.Count > 0
                ? gmc.TypeArguments
                : null,
            ResolvedType = gmc.ResolvedType,
            IsInFlight = gmc.IsInFlight
        };
    }

    /// <summary>
    /// Lowers a resolved memberRoutine-generic call on a receiver (e.g. <c>buf.read![U8](offset)</c>)
    /// to a plain <see cref="CallExpression"/> over a <see cref="MemberExpression"/> callee.
    /// </summary>
    private CallExpression LowerMemberRoutineCall(GenericMemberRoutineCallExpression gmc,
        List<Expression> loweredArgs)
    {
        Expression loweredObj = VisitExpression(expr: gmc.Object);

        return new CallExpression(
            Callee: new MemberExpression(Object: loweredObj,
                MemberName: gmc.MemberRoutineName,
                Location: gmc.Location)
            {
                ResolvedType = gmc.Object.ResolvedType, IsFailable = gmc.IsMemoryOperation
            },
            Arguments: loweredArgs,
            Location: gmc.Location)
        {
            IsFailable = gmc.IsMemoryOperation,
            LoweringKind = gmc.LoweringKind,
            ConstructedType = gmc.ConstructedType,
            ResolvedRoutine = gmc.ResolvedRoutine,
            TypeArguments = gmc.TypeArguments.Count > 0
                ? gmc.TypeArguments
                : null,
            ResolvedType = gmc.ResolvedType,
            IsInFlight = gmc.IsInFlight
        };
    }

    /// <summary>
    /// Re-instantiates a memberRoutine-generic <c>ResolvedRoutine</c> from the call's explicit type
    /// arguments when it is still a generic definition (or owned by one). Returns the original
    /// routine when it is already concrete or the type args can't be resolved.
    /// </summary>
    private RoutineInfo? ConcretizeMemberRoutineGenericRoutine(
        GenericMemberRoutineCallExpression gmc)
    {
        RoutineInfo? routine = gmc.ResolvedRoutine;
        if (!IsUnconcretizedMemberRoutineGeneric(routine: routine))
        {
            return routine;
        }

        RoutineInfo genDef = routine!.GenericDefinition ?? routine;
        if (!genDef.IsGenericDefinition || genDef.GenericParameters is not { Count: > 0 } gp ||
            gp.Count != gmc.TypeArguments.Count)
        {
            return routine;
        }

        var args = new List<TypeSymbol>(capacity: gmc.TypeArguments.Count);
        foreach (TypeExpression te in gmc.TypeArguments)
        {
            TypeSymbol? arg = te.ResolvedType is { } rt and not ErrorTypeSymbol
                ? rt
                : _registry.LookupType(name: te.Name);
            if (arg == null || arg is ErrorTypeSymbol || ContainsGenericParam(t: arg))
            {
                return routine;
            }

            args.Add(item: arg);
        }

        return _registry.GetOrCreateRoutineResolution(genericDef: genDef, typeArguments: args) ??
               routine;
    }

    /// <summary>
    /// True when a resolved routine still needs its memberRoutine-level type param bound from an explicit
    /// call type-argument: it is a generic definition, is owned by one, OR (the concrete-owner case
    /// like <c>Hijacked[BTreeListNode[S64]].recast_as() -&gt; Hijacked[U]</c>) still carries a
    /// generic parameter in its return or parameter types.
    /// </summary>
    private static bool IsUnconcretizedMemberRoutineGeneric(RoutineInfo? routine)
    {
        if (routine is null or { IsGenericDefinition: true } or
            { OwnerType.IsGenericDefinition: true })
        {
            return routine != null;
        }

        if (routine.ReturnType != null && ContainsGenericParam(t: routine.ReturnType))
        {
            return true;
        }

        return routine.Parameters.Any(predicate: p =>
            p.Type != null && ContainsGenericParam(t: p.Type));
    }

    private static bool ContainsGenericParam(TypeSymbol t)
    {
        if (t is GenericParameterTypeSymbol)
        {
            return true;
        }

        if (t is { IsGenericDefinition: true, GenericParameters.Count: > 0 })
        {
            return true;
        }

        return t.TypeArguments is { Count: > 0 } a &&
               a.Any(predicate: x => ContainsGenericParam(t: x));
    }

    /// <summary>
    /// Falls through to just lowering the children of an un-lowerable
    /// <see cref="GenericMemberRoutineCallExpression"/>.
    /// </summary>
    private GenericMemberRoutineCallExpression LowerGenericCallChildren(
        GenericMemberRoutineCallExpression gmc)
    {
        Expression loweredObj = VisitExpression(expr: gmc.Object);
        bool argsChanged = false;
        var args = new List<Expression>(capacity: gmc.Arguments.Count);
        foreach (Expression arg in gmc.Arguments)
        {
            Expression lowered = VisitExpression(expr: arg);
            args.Add(item: lowered);
            argsChanged |= !ReferenceEquals(objA: lowered, objB: arg);
        }

        bool changed = !ReferenceEquals(objA: loweredObj, objB: gmc.Object) || argsChanged;
        return changed
            ? gmc with { Object = loweredObj, Arguments = args }
            : gmc;
    }
}
