using System.Collections.Generic;
using System.Linq;
using Compiler.Postprocessing.Passes;
using Compiler.Instantiation;
using Compiler.Resolution;
using SyntaxTree;
using TypeModel.Symbols;
using TypeModel.Types;

namespace Compiler.Desugaring.Passes;

/// <summary>
/// Lowers <see cref="GenericMemberRoutineCallExpression"/> nodes to plain <see cref="CallExpression"/>
/// nodes where possible. Runs after <see cref="ExpressionLoweringPass"/> in the per-file pipeline.
///
/// <para>Lowered cases (require <c>ResolvedRoutine != null</c> from Phase 4):</para>
/// <list type="bullet">
/// <item><b>Type constructor with resolved <c>create</c></b>:
/// <c>Maybe[S64](value: x)</c> -> <c>CallExpression(IdentifierExpression("create"), args)</c></item>
/// <item><b>Generic memberRoutine call on receiver</b>:
/// <c>buf.read![U8](offset)</c> ??
/// <c>CallExpression(MemberExpression(buf, "read!"), args, TypeArguments=[U8])</c></item>
/// </list>
///
/// <para>Kept as <see cref="GenericMemberRoutineCallExpression"/> (not lowered):</para>
/// <list type="bullet">
/// <item>Collection literals -> <c>IsCollectionLiteral == true</c>;
/// codegen emits <c>create + add_last</c> loops.</item>
/// <item>Unresolved calls -> <c>ResolvedRoutine == null</c> and no safe lowering target
/// has been determined yet.</item>
/// </list>
/// </summary>
internal sealed class GenericCallLoweringPass
{
    /// <summary>
    /// Stores the registry state used by this compiler phase.
    /// </summary>
    private readonly TypeRegistry _registry;
    private readonly Dictionary<string, Statement> _variantBodies;
    private readonly Dictionary<string, MonomorphizedBody>? _instantiatedGenericBodies;

    /// <summary>
    /// Initializes a new instance with the dependencies required for its compiler phase.
    /// </summary>
    public GenericCallLoweringPass(DesugaringContext ctx)
        : this(ctx.Registry, ctx.VariantBodies, ctx.InstantiatedGenericBodies) { }

    /// <summary>
    /// Initializes a new instance with the dependencies required for its compiler phase.
    /// </summary>
    public GenericCallLoweringPass(TypeRegistry registry, Dictionary<string, Statement> variantBodies)
        : this(registry, variantBodies, null) { }

    /// <summary>
    /// Initializes a new instance with the dependencies required for its compiler phase.
    /// </summary>
    private GenericCallLoweringPass(TypeRegistry registry, Dictionary<string, Statement> variantBodies,
        Dictionary<string, MonomorphizedBody>? instantiatedGenericBodies)
    {
        _registry = registry;
        _variantBodies = variantBodies;
        _instantiatedGenericBodies = instantiatedGenericBodies;
    }

    /// <summary>
    /// Runs this compiler phase over its configured input.
    /// </summary>
    public void Run(Program program)
    {
        for (int i = 0; i < program.Declarations.Count; i++)
        {
            switch (program.Declarations[i])
            {
                case RoutineDeclaration r:
                {
                    Statement newBody = LowerStatement(r.Body);
                    if (!ReferenceEquals(newBody, r.Body))
                        program.Declarations[i] = r with { Body = newBody };
                    break;
                }

                case EntityDeclaration e:
                    LowerMemberList(e.Members);
                    break;

                case RecordDeclaration rec:
                    LowerMemberList(rec.Members);
                    break;

                case CrashableDeclaration cr:
                    LowerMemberList(cr.Members);
                    break;
            }
        }
    }

    /// <summary>
    /// Lowers GMCEs in all variant bodies generated by ErrorHandlingVariantPass.
    /// Must run after SA so that ResolvedRoutine is set on GMCEs that SA resolved.
    /// </summary>
    public void RunOnVariantBodies()
    {
        foreach (string key in _variantBodies.Keys.ToList())
        {
            Statement body = _variantBodies[key];
            Statement lowered = LowerStatement(body);
            if (!ReferenceEquals(lowered, body))
                _variantBodies[key] = lowered;
        }
    }

    /// <summary>
    /// Lowers GMCEs in all instantiated generic bodies produced during Phase 7.
    /// These bodies must meet the same backend-entry contract as ordinary programs.
    /// </summary>
    public void RunOnInstantiatedGenericBodies()
    {
        if (_instantiatedGenericBodies == null)
        {
            return;
        }

        foreach (string key in _instantiatedGenericBodies.Keys.ToList())
        {
            MonomorphizedBody body = _instantiatedGenericBodies[key];
            // NOTE: Previously skipped synthesized bodies (assumed they never contained GMCEs),
            // but wrapper represent/diagnose forwarders synthesized by WiredRoutinePass /
            // wrapper-forwarder synthesis DO contain GMCEs (e.g. Hijacked[T].x calls). Lower
            // them too so they meet the codegen contract.
            Statement lowered = LowerStatement(body.Ast.Body);
            if (!ReferenceEquals(lowered, body.Ast.Body))
            {
                _instantiatedGenericBodies[key] = body with
                {
                    Ast = body.Ast with { Body = lowered }
                };
            }
        }
    }

    /// <summary>
    /// Lower member list as part of this compiler phase.
    /// </summary>
    private void LowerMemberList(List<SyntaxTree.Declaration> members)
    {
        for (int j = 0; j < members.Count; j++)
        {
            if (members[j] is not RoutineDeclaration m) continue;
            Statement newBody = LowerStatement(m.Body);
            if (!ReferenceEquals(newBody, m.Body))
                members[j] = m with { Body = newBody };
        }
    }

    // -----------------------------------------------------------------------------

    /// <summary>
    /// Lower statement as part of this compiler phase.
    /// </summary>
    private Statement LowerStatement(Statement stmt)
    {
        switch (stmt)
        {
            case BlockStatement b:
            {
                List<Statement> stmts = LowerStatementList(b.Statements);
                return ReferenceEquals(stmts, b.Statements) ? stmt : b with { Statements = stmts };
            }

            case IfStatement ifs:
            {
                Expression cond = LowerExpression(ifs.Condition);
                Statement then = LowerStatement(ifs.ThenStatement);
                Statement? elseS = ifs.ElseStatement != null
                    ? LowerStatement(ifs.ElseStatement)
                    : null;
                bool changed = !ReferenceEquals(cond, ifs.Condition)
                               || !ReferenceEquals(then, ifs.ThenStatement)
                               || !ReferenceEquals(elseS, ifs.ElseStatement);
                return changed
                    ? ifs with { Condition = cond, ThenStatement = then, ElseStatement = elseS }
                    : stmt;
            }

            case WhileStatement w:
            {
                Expression cond = LowerExpression(w.Condition);
                Statement body = LowerStatement(w.Body);
                Statement? elseB = w.ElseBranch != null ? LowerStatement(w.ElseBranch) : null;
                bool changed = !ReferenceEquals(cond, w.Condition)
                               || !ReferenceEquals(body, w.Body)
                               || !ReferenceEquals(elseB, w.ElseBranch);
                return changed ? w with { Condition = cond, Body = body, ElseBranch = elseB } : stmt;
            }

            case LoopStatement loop:
            {
                Statement body = LowerStatement(loop.Body);
                return ReferenceEquals(body, loop.Body) ? stmt : loop with { Body = body };
            }

            case WhenStatement w:
            {
                Expression subj = LowerExpression(w.Expression);
                bool clauseChanged = false;
                var clauses = new List<WhenClause>(capacity: w.Clauses.Count);
                foreach (WhenClause c in w.Clauses)
                {
                    Statement lBody = LowerStatement(c.Body);
                    clauseChanged |= !ReferenceEquals(lBody, c.Body);
                    clauses.Add(ReferenceEquals(lBody, c.Body) ? c : c with { Body = lBody });
                }
                bool changed = !ReferenceEquals(subj, w.Expression) || clauseChanged;
                return changed ? w with { Expression = subj, Clauses = clauses } : stmt;
            }

            case ReturnStatement r:
            {
                if (r.Value == null) return stmt;
                Expression val = LowerExpression(r.Value);
                return ReferenceEquals(val, r.Value) ? stmt : r with { Value = val };
            }

            case VariantReturnStatement { Value: not null } vrs:
            {
                Expression val = LowerExpression(vrs.Value);
                return ReferenceEquals(val, vrs.Value) ? stmt : vrs with { Value = val };
            }

            case ExpressionStatement es:
            {
                Expression e = LowerExpression(es.Expression);
                return ReferenceEquals(e, es.Expression) ? stmt : es with { Expression = e };
            }

            case AssignmentStatement a:
            {
                Expression val = LowerExpression(a.Value);
                // Target is usually not a GenericMemberRoutineCallExpression; walk it anyway
                Expression tgt = LowerExpression(a.Target);
                bool changed = !ReferenceEquals(val, a.Value) || !ReferenceEquals(tgt, a.Target);
                return changed ? a with { Target = tgt, Value = val } : stmt;
            }

            case DeclarationStatement { Declaration: VariableDeclaration vd } decl:
            {
                if (vd.Initializer == null) return stmt;
                Expression init = LowerExpression(vd.Initializer);
                if (ReferenceEquals(init, vd.Initializer)) return stmt;
                return decl with { Declaration = vd with { Initializer = init } };
            }

            case DiscardStatement d:
            {
                Expression e = LowerExpression(d.Expression);
                return ReferenceEquals(e, d.Expression) ? stmt : d with { Expression = e };
            }

            case DangerStatement danger:
            {
                Statement body = LowerStatement(danger.Body);
                return ReferenceEquals(body, danger.Body) ? stmt : danger with { Body = (BlockStatement)body };
            }

            default:
                return stmt;
        }
    }

    /// <summary>
    /// Lower statement list as part of this compiler phase.
    /// </summary>
    private List<Statement> LowerStatementList(List<Statement> stmts)
    {
        bool changed = false;
        var result = new List<Statement>(capacity: stmts.Count);
        foreach (Statement s in stmts)
        {
            Statement lowered = LowerStatement(s);
            changed |= !ReferenceEquals(lowered, s);
            result.Add(lowered);
        }
        return changed ? result : stmts;
    }

    // -----------------------------------------------------------------------------

    /// <summary>
    /// Lower expression as part of this compiler phase.
    /// </summary>
    private Expression LowerExpression(Expression expr) // NOSONAR S3776
    {
        switch (expr)
        {
            case GenericMemberRoutineCallExpression gmc:
                return TryLowerGenericCall(gmc) ?? LowerGenericCallChildren(gmc);

            case CallExpression call:
            {
                Expression callee = LowerExpression(call.Callee);
                bool argsChanged = false;
                var args = new List<Expression>(capacity: call.Arguments.Count);
                foreach (Expression arg in call.Arguments)
                {
                    Expression lowered = LowerExpression(arg);
                    args.Add(lowered);
                    argsChanged |= !ReferenceEquals(lowered, arg);
                }
                bool changed = !ReferenceEquals(callee, call.Callee) || argsChanged;
                if (!changed) return expr;
                var rewritten = call with { Callee = callee, Arguments = args };
                // ResolvedRoutine/ResolvedType/etc. are mutable {get;set;} props — `with` drops them.
                rewritten.ResolvedRoutine = call.ResolvedRoutine;
                rewritten.LoweringKind = call.LoweringKind;
                rewritten.ConstructedType = call.ConstructedType;
                rewritten.IsCollectionLiteral = call.IsCollectionLiteral;
                rewritten.TypeArguments = call.TypeArguments;
                rewritten.ResolvedType = call.ResolvedType;
                return rewritten;
            }

            case MemberExpression me:
            {
                Expression obj = LowerExpression(me.Object);
                if (ReferenceEquals(obj, me.Object)) return expr;
                var rewritten = me with { Object = obj };
                rewritten.ResolvedType = me.ResolvedType;
                return rewritten;
            }

            case BinaryExpression bin:
            {
                Expression left = LowerExpression(bin.Left);
                Expression right = LowerExpression(bin.Right);
                bool changed = !ReferenceEquals(left, bin.Left) || !ReferenceEquals(right, bin.Right);
                return changed ? bin with { Left = left, Right = right } : expr;
            }

            case UnaryExpression u:
            {
                Expression operand = LowerExpression(u.Operand);
                return ReferenceEquals(operand, u.Operand) ? expr : u with { Operand = operand };
            }

            case ConditionalExpression cond:
            {
                Expression c = LowerExpression(cond.Condition);
                Expression t = LowerExpression(cond.TrueExpression);
                Expression f = LowerExpression(cond.FalseExpression);
                bool changed = !ReferenceEquals(c, cond.Condition)
                               || !ReferenceEquals(t, cond.TrueExpression)
                               || !ReferenceEquals(f, cond.FalseExpression);
                return changed
                    ? cond with { Condition = c, TrueExpression = t, FalseExpression = f }
                    : expr;
            }

            case NamedArgumentExpression named:
            {
                Expression val = LowerExpression(named.Value);
                return ReferenceEquals(val, named.Value) ? expr : named with { Value = val };
            }

            case InsertedTextExpression inserted:
            {
                // f-string interpolations: a `{ expr }` part can hold a GenericMemberRoutineCallExpression
                // (e.g. `f"…{words.min_by[U64](selector: …)}…"`). Without recursing into the parts
                // that GMCE survives to codegen and trips the "GenericMemberRoutineCallExpression survived
                // postprocessing" guard.
                bool partChanged = false;
                var newParts = new List<InsertedTextPart>(capacity: inserted.Parts.Count);
                foreach (InsertedTextPart part in inserted.Parts)
                {
                    if (part is ExpressionPart ep)
                    {
                        Expression loweredPart = LowerExpression(ep.Expression);
                        if (!ReferenceEquals(loweredPart, ep.Expression))
                        {
                            partChanged = true;
                            newParts.Add(item: ep with { Expression = loweredPart });
                            continue;
                        }
                    }
                    newParts.Add(item: part);
                }
                return partChanged ? inserted with { Parts = newParts } : expr;
            }

            case CreatorExpression creator:
            {
                // Constructor arguments can themselves be GMCEs (e.g.
                // `Limbs[4](d: Array[U32, 4]())`). Without recursing into the member
                // values, a nested GMCE survives to codegen and trips the
                // "GenericMemberRoutineCallExpression reached codegen" guard.
                bool membersChanged = false;
                var newMembers =
                    new List<(string Name, Expression Value)>(capacity: creator.MemberVariables.Count);
                foreach ((string name, Expression value) in creator.MemberVariables)
                {
                    Expression lowered = LowerExpression(value);
                    membersChanged |= !ReferenceEquals(lowered, value);
                    newMembers.Add(item: (name, lowered));
                }
                if (!membersChanged) return expr;
                var rewritten = creator with { MemberVariables = newMembers };
                // Mutable {get;set;} props are dropped by `with` — carry them over.
                rewritten.LoweringKind = creator.LoweringKind;
                rewritten.ConstructedType = creator.ConstructedType;
                rewritten.ResolvedCreatorRoutine = creator.ResolvedCreatorRoutine;
                rewritten.ResolvedType = creator.ResolvedType;
                return rewritten;
            }

            default:
                return expr;
        }
    }

    /// <summary>
    /// Returns true when <paramref name="type"/> is a record/entity with no member variables —
    /// so a zero-arg <see cref="CreatorExpression"/> over it is structurally valid (a bare
    /// zero-init of the type's storage). Returns false for null and for types that carry
    /// fields needing initialization.
    /// </summary>
    private static bool HasZeroMemberVariables(TypeInfo? type)
    {
        return type switch
        {
            RecordTypeInfo r => r.MemberVariables.Count == 0,
            EntityTypeInfo e => e.MemberVariables.Count == 0,
            _ => false
        };
    }

    /// <summary>
    /// Tries to lower a <see cref="GenericMemberRoutineCallExpression"/> to a plain
    /// <see cref="CallExpression"/>. Returns <c>null</c> if the node cannot be safely lowered.
    /// </summary>
    private Expression? TryLowerGenericCall(GenericMemberRoutineCallExpression gmc)
    {
        // Collection literals need special codegen (create + add_last loop).
        if (gmc.IsCollectionLiteral) return null;

        // -----------------------------------------------------------------------------
        // SA finds no matching create overload (e.g. List[T](data:..., count:..., capacity:...))
        // because this is a raw field-initialization form, not a regular routine call.
        // Lower to CreatorExpression so codegen's EmitConstructorCall handles it.
        // Also covers zero-arg construction of zero-field records and const-generic record
        // resolutions (e.g. BitArray[8](), Array[S64, 4]()) — SA marks these as type
        // constructions via ConstructedType/LoweringKind=TypeConstructor but never finds a
        // matching create() to bind ResolvedRoutine. Without lowering they'd survive as
        // GMCEs and trip the IllegalBackendResidualNode check.
        //
        // Zero-arg construction of a type that has fields (e.g. Deque[S64]()) is NOT lowered
        // here — the type relies on a real create() overload that SA failed to bind, and
        // forging an empty CreatorExpression would just re-issue the bug as S455
        // (missing field). Leave that case to the SA fix path.
        // A FAILABLE construction `Type![Args](args)` (IsMemoryOperation) must NOT be lowered to a
        // field-init CreatorExpression here — it routes to the type's failable `create!` overload
        // (e.g. the variant-arm extractor `Dict[Text, SerialValue].create!(from: sv)`). Leave it as a
        // GMC so SA resolves the creator; SA-time lowering (below, once ResolvedRoutine is set) or the
        // creator-routing path handles it.
        if (gmc.Object is IdentifierExpression literalId && literalId.Name == gmc.MemberRoutineName
            && !gmc.IsMemoryOperation
            && gmc.ResolvedRoutine == null
            && _registry.LookupType(name: gmc.MemberRoutineName) != null
            && (gmc.Arguments.Count > 0
                || HasZeroMemberVariables(type: gmc.ConstructedType)))
        {
            // Accept either fully named args (record-style field init) or fully positional
            // (constructor call form like Hijacked[T](me) from synthesized wrapper bodies).
            // CreatorExpression's MemberVariables uses ("", expr) for positional entries.
            bool allNamed = gmc.Arguments.All(predicate: a => a is NamedArgumentExpression);
            bool anyNamed = gmc.Arguments.Any(predicate: a => a is NamedArgumentExpression);
            if (!allNamed && anyNamed) return null; // mixed named/positional — not our case

            var members = new List<(string Name, Expression Value)>(capacity: gmc.Arguments.Count);
            foreach (Expression arg in gmc.Arguments)
            {
                if (arg is NamedArgumentExpression named)
                    members.Add((named.Name, LowerExpression(named.Value)));
                else
                    members.Add(("", LowerExpression(arg)));
            }
            return new CreatorExpression(
                TypeName: gmc.MemberRoutineName,
                TypeArguments: gmc.TypeArguments.Count > 0 ? gmc.TypeArguments : null,
                MemberVariables: members,
                Location: gmc.Location)
            {
                LoweringKind = gmc.LoweringKind,
                ConstructedType = gmc.ConstructedType,
                ResolvedType = gmc.ResolvedType,
                IsInFlight = gmc.IsInFlight
            };
        }

        // Only lower when SA has resolved the routine -> provides the concrete call target.
        if (gmc.ResolvedRoutine == null) return null;

        // A memberRoutine-generic call (`recast_as[T]`) whose ResolvedRoutine is still the generic-def
        // (its type param comes from the explicit `[T]` arg, so owner substitution alone can't
        // concretize it) must be re-instantiated from its now-concrete type arguments before it is
        // baked into a plain CallExpression — otherwise codegen receives a generic-def callee.
        gmc = gmc with { ResolvedRoutine = ConcretizeMemberRoutineGenericRoutine(gmc) };

        // Lower arguments first.
        var loweredArgs = new List<Expression>(capacity: gmc.Arguments.Count);
        foreach (Expression arg in gmc.Arguments)
            loweredArgs.Add(LowerExpression(arg));

        // -----------------------------------------------------------------------------
        // e.g., Maybe[S64](present: true, value: x) -> SA resolved create and set ResolvedRoutine.
        // Also handles standalone generic free routines and LLVM intrinsic free functions where
        // Object.Name == memberRoutineName but there is no constructable type.
        // A failable generic construction `Type![Args](args)` parses with a BARE memberRoutineName equal to
        // the type name plus the structured IsMemoryOperation failable flag; treat it like the
        // construction case (same as `Type[Args](args)`) so its arguments are passed straight to the
        // resolved `create!` instead of being mis-lowered into a member call whose receiver (the type
        // name) becomes a null first argument.
        if (gmc.Object is IdentifierExpression id && id.Name == gmc.MemberRoutineName)
        {
            bool isTypeConstruction = gmc.ConstructedType != null ||
                                      gmc.LoweringKind is CallLoweringKind.TypeConstructor
                                          or CallLoweringKind.WrapperConstruction
                                          or CallLoweringKind.ValueConversion
                                          or CallLoweringKind.CollectionConstruction;
            return new CallExpression(
                // Callee is the type name (without the failable `!`); codegen constructs via
                // ConstructedType/ResolvedRoutine, so the name only identifies the type.
                Callee: new IdentifierExpression(
                    Name: isTypeConstruction ? id.Name : gmc.ResolvedRoutine.Name,
                    Location: gmc.Location,
                    // Preserve the `::` realm qualifier (`LLVM::add[U128]`) so a re-analysis of the
                    // lowered body (monomorphized stdlib bodies re-run SA post-lowering) still sees the
                    // foreign realm and the strict realm gate passes instead of false-flagging.
                    Realm: id.Realm),
                Arguments: loweredArgs,
                Location: gmc.Location)
            {
                IsFailable = gmc.IsMemoryOperation,
                LoweringKind = gmc.LoweringKind,
                ConstructedType = gmc.ConstructedType,
                ResolvedRoutine = gmc.ResolvedRoutine,
                TypeArguments = gmc.TypeArguments.Count > 0 ? gmc.TypeArguments : null,
                ResolvedType = gmc.ResolvedType,
                IsInFlight = gmc.IsInFlight
            };
        }

        // -----------------------------------------------------------------------------
        // e.g., buf.read![U8](offset) -> CallExpression with TypeArguments=[U8].
        Expression loweredObj = LowerExpression(gmc.Object);

        return new CallExpression(
            Callee: new MemberExpression(
                Object: loweredObj,
                MemberName: gmc.MemberRoutineName,
                Location: gmc.Location)
            {
                ResolvedType = gmc.Object.ResolvedType,
                IsFailable = gmc.IsMemoryOperation
            },
            Arguments: loweredArgs,
            Location: gmc.Location)
        {
            IsFailable = gmc.IsMemoryOperation,
            LoweringKind = gmc.LoweringKind,
            ConstructedType = gmc.ConstructedType,
            ResolvedRoutine = gmc.ResolvedRoutine,
            TypeArguments = gmc.TypeArguments.Count > 0 ? gmc.TypeArguments : null,
            ResolvedType = gmc.ResolvedType,
            IsInFlight = gmc.IsInFlight
        };
    }

    /// <summary>
    /// Re-instantiates a memberRoutine-generic <c>ResolvedRoutine</c> from the call's explicit type
    /// arguments when it is still a generic definition (or owned by one). Returns the original
    /// routine when it is already concrete or the type args can't be resolved.
    /// </summary>
    private RoutineInfo? ConcretizeMemberRoutineGenericRoutine(GenericMemberRoutineCallExpression gmc)
    {
        RoutineInfo? routine = gmc.ResolvedRoutine;
        if (!IsUnconcretizedMemberRoutineGeneric(routine))
        {
            return routine;
        }
        RoutineInfo genDef = routine!.GenericDefinition ?? routine;
        if (!genDef.IsGenericDefinition || genDef.GenericParameters is not { Count: > 0 } gp
            || gp.Count != gmc.TypeArguments.Count)
        {
            return routine;
        }

        var args = new List<TypeInfo>(capacity: gmc.TypeArguments.Count);
        foreach (TypeExpression te in gmc.TypeArguments)
        {
            TypeInfo? arg = te.ResolvedType is { } rt and not ErrorTypeInfo
                ? rt
                : _registry.LookupType(name: te.Name);
            if (arg == null || arg is ErrorTypeInfo || ContainsGenericParam(arg))
                return routine;
            args.Add(item: arg);
        }
        return _registry.GetOrCreateRoutineResolution(genericDef: genDef, typeArguments: args)
               ?? routine;
    }

    /// <summary>
    /// True when a resolved routine still needs its memberRoutine-level type param bound from an explicit
    /// call type-argument: it is a generic definition, is owned by one, OR (the concrete-owner case
    /// like <c>Hijacked[BTreeListNode[S64]].recast_as() -&gt; Hijacked[U]</c>) still carries a
    /// generic parameter in its return or parameter types.
    /// </summary>
    private static bool IsUnconcretizedMemberRoutineGeneric(RoutineInfo? routine)
    {
        if (routine is null or { IsGenericDefinition: true } or { OwnerType.IsGenericDefinition: true })
            return routine != null;
        if (routine.ReturnType != null && ContainsGenericParam(routine.ReturnType))
            return true;
        return routine.Parameters.Any(p => p.Type != null && ContainsGenericParam(p.Type));
    }

    private static bool ContainsGenericParam(TypeInfo t)
    {
        if (t is GenericParameterTypeInfo) return true;
        if (t is { IsGenericDefinition: true, GenericParameters.Count: > 0 }) return true;
        return t.TypeArguments is { Count: > 0 } a && a.Any(x => ContainsGenericParam(t: x));
    }

    /// <summary>
    /// Falls through to just lowering the children of an un-lowerable
    /// <see cref="GenericMemberRoutineCallExpression"/>.
    /// </summary>
    private GenericMemberRoutineCallExpression LowerGenericCallChildren(GenericMemberRoutineCallExpression gmc)
    {
        Expression loweredObj = LowerExpression(gmc.Object);
        bool argsChanged = false;
        var args = new List<Expression>(capacity: gmc.Arguments.Count);
        foreach (Expression arg in gmc.Arguments)
        {
            Expression lowered = LowerExpression(arg);
            args.Add(lowered);
            argsChanged |= !ReferenceEquals(lowered, arg);
        }

        bool changed = !ReferenceEquals(loweredObj, gmc.Object) || argsChanged;
        return changed ? gmc with { Object = loweredObj, Arguments = args } : gmc;
    }
}
