using Builder.Desugaring.Passes;
using SyntaxTree;
using Builder.Instantiation;

namespace Builder.Desugaring;

/// <summary>
/// Phase 3 pipeline: syntax-only lowering that requires no type information.
/// Runs per-file before semantic analysis annotates ResolvedType.
/// </summary>
public sealed class DesugaringPipeline(DesugaringContext ctx)
{
    /// <summary>
    /// Phase 3 per-file passes. Order:
    /// <list type="number">
    ///   <item><see cref="NoneReturnNormalizationPass"/> — fills null return types and bare returns with <c>None</c>.</item>
    ///   <item><see cref="PresetInliningPass"/> — substitutes preset identifiers with literal values.</item>
    ///   <item><see cref="ControlFlowLoweringPass"/> — lowers for-loops and while to loop+if primitives.</item>
    ///   <item><see cref="GenericCallLoweringPass"/> — lowers <c>GenericMemberRoutineCallExpression</c> to <c>CallExpression</c>.</item>
    /// </list>
    /// </summary>
    public void Run(Program program)
    {
        new NoneReturnNormalizationPass(_: ctx).Run(program: program);
        new PresetInliningPass(ctx: ctx).Run(program: program);
        new ControlFlowLoweringPass(ctx: ctx).Run(program: program);
        new GenericCallLoweringPass(ctx: ctx).Run(program: program);
    }

    /// <summary>
    /// Phase 6 global synthesis: runs once after all per-file Phase 4 analysis.
    /// Generates error-handling variants, wired routine bodies, prunes unused generics,
    /// then applies Phase 3 passes to the generated variant bodies and stdlib programs.
    /// Phase 8 variant-body and stdlib lowering is handled by
    /// <see cref="Builder.Lowering.PostprocessingPipeline.RunGlobal"/>.
    /// </summary>
    public void RunGlobal()
    {
        new ErrorHandlingVariantPass(ctx: ctx).RunGlobal();
        ctx.Registry.PruneUnusedGenericRoutines();

        foreach (string key in ctx.VariantBodies.Keys.ToList())
        {
            string baseName = key.Contains(value: '#')
                ? key[..key.IndexOf(value: '#')]
                : key;
            if (ctx.Registry.IsRoutinePruned(baseName: baseName))
            {
                ctx.VariantBodies.Remove(key: key);
            }
        }

        // Phase 3 on variant bodies generated by ErrorHandlingVariantPass.
        new PresetInliningPass(ctx: ctx).RunOnVariantBodies();
        new ControlFlowLoweringPass(ctx: ctx).RunOnVariantBodies();
        new GenericCallLoweringPass(ctx: ctx).RunOnVariantBodies();

        // Phase 3 on freshly-loaded stdlib programs (cold: all; warm-restore: only on-demand imports —
        // the restored programs are already desugared).
        // STAGE-5 FLIP (pull/(B)): the collector drives per-file stdlib desugaring on reach
        // (SemanticVerifier.AnalyzeStdlibProgramOnDemand runs DesugaringPipeline.Run per file), so skip the
        // eager stdlib sweep here — only user + variant global lowering stays (demand collector drives stdlib per-file).
        // BASE build (SynthesizeAllDerives) stays eager — it must desugar the WHOLE stdlib, not a demand slice.
        if (!ctx.SynthesizeAllDerives)
        {
            return;
        }

        foreach ((Program program, _, _) in ctx.Registry.FreshlyLoadedStdlibPrograms)
        {
            new NoneReturnNormalizationPass(_: ctx).Run(program: program);
            new PresetInliningPass(ctx: ctx).Run(program: program);
            new ControlFlowLoweringPass(ctx: ctx).Run(program: program);
            new GenericCallLoweringPass(ctx: ctx).Run(program: program);
        }
    }
}
