using Compiler.Desugaring.Passes;
using Compiler.Synthesis;
using SyntaxTree;

namespace Compiler.Desugaring;

/// <summary>
/// Phase 3 pipeline: syntax-only lowering that requires no type information.
/// Runs per-file before semantic analysis annotates ResolvedType.
/// </summary>
public sealed class DesugaringPipeline(DesugaringContext ctx)
{
    /// <summary>
    /// Phase 3 per-file passes. Order:
    /// <list type="number">
    ///   <item><see cref="BlankReturnNormalizationPass"/> — fills null return types and bare returns with <c>Blank</c>.</item>
    ///   <item><see cref="PresetInliningPass"/> — substitutes preset identifiers with literal values.</item>
    ///   <item><see cref="ControlFlowLoweringPass"/> — lowers for-loops and while to loop+if primitives.</item>
    ///   <item><see cref="GenericCallLoweringPass"/> — lowers <c>GenericMethodCallExpression</c> to <c>CallExpression</c>.</item>
    /// </list>
    /// </summary>
    public void Run(Program program)
    {
        new BlankReturnNormalizationPass(ctx).Run(program);
        new PresetInliningPass(ctx).Run(program);
        new ControlFlowLoweringPass(ctx).Run(program);
        new GenericCallLoweringPass(ctx).Run(program);
    }

    /// <summary>
    /// Phase 4 global synthesis: runs once after all per-file Phase 5 analysis.
    /// Generates error-handling variants, wired routine bodies, prunes unused generics,
    /// then applies Phase 3 passes to the generated variant bodies and stdlib programs.
    /// Phase 7 variant-body and stdlib lowering is handled by
    /// <see cref="Compiler.Postprocessing.PostprocessingPipeline.RunGlobal"/>.
    /// </summary>
    public void RunGlobal()
    {
        new ErrorHandlingVariantPass(ctx).RunGlobal();
        new WiredRoutinePass(ctx).RunGlobal();
        ctx.Registry.PruneUnusedGenericRoutines();

        foreach (string key in ctx.VariantBodies.Keys.ToList())
        {
            string baseName = key.Contains(value: '#') ? key[..key.IndexOf(value: '#')] : key;
            if (ctx.Registry.IsRoutinePruned(baseName: baseName))
                ctx.VariantBodies.Remove(key: key);
        }

        // Phase 3 on variant bodies generated by ErrorHandlingVariantPass.
        new PresetInliningPass(ctx).RunOnVariantBodies();
        new ControlFlowLoweringPass(ctx).RunOnVariantBodies();
        new GenericCallLoweringPass(ctx).RunOnVariantBodies();

        // Phase 3 on stdlib programs (bypassed per-file desugaring since pre-loaded by StdlibLoader).
        foreach ((Program program, _, _) in ctx.Registry.StdlibPrograms)
        {
            new BlankReturnNormalizationPass(ctx).Run(program);
            new PresetInliningPass(ctx).Run(program);
            new ControlFlowLoweringPass(ctx).Run(program);
            new GenericCallLoweringPass(ctx).Run(program);
        }
    }
}