namespace Compiler.CodeGen;

using System.Text;
using SemanticVerification.Symbols;
using SemanticVerification.Types;
using SyntaxTree;

/// <summary>
/// Declaration code generation for synthesized equality and lookup-style routines.
/// </summary>
public partial class LLVMCodeGenerator
{
/// <summary>
    /// Generates LLVM IR bodies for all synthesized routines.
    /// These routines are registered by the semantic analyzer (Phase 2.55/2.6) with IsSynthesized = true
    /// but have no AST body — their IR is emitted directly here.
    /// </summary>
    private void GenerateSynthesizedRoutines()
    {
        foreach (RoutineInfo routine in _registry.GetAllRoutines())
        {
            // Process routines that are either IsSynthesized (wired stubs, derived operators)
            // OR have an explicit AST body in _synthesizedBodies (try_/check_/lookup_ variants
            // for concrete stdlib types, generated by ErrorHandlingGenerator).
            bool hasSynthesizedBody = _synthesizedBodies.ContainsKey(key: routine.RegistryKey);
            if (!routine.IsSynthesized && !hasSynthesizedBody)
            {
                continue;
            }

            // Skip generic definitions, routines with error types,
            // and routines on generic owner types (e.g., List[T].$diagnose)
            if (routine.IsGenericDefinition || HasErrorTypes(routine: routine) ||
                routine.OwnerType is { IsGenericDefinition: true })
            {
                continue;
            }

            string funcName = MangleFunctionName(routine: routine);

            // Only emit synthesized routines that were declared (actually referenced)
            if (!_generatedFunctions.Contains(item: funcName))
            {
                continue;
            }

            // Skip if already generated
            if (!_generatedFunctionDefs.Add(item: funcName))
            {
                continue;
            }

            // Mark in declarations set to prevent declare/define conflicts
            _generatedFunctions.Add(item: funcName);

            EmitSynthesizedRoutineBody(routine: routine, funcName: funcName);
        }
    }

    /// <summary>
    /// Emits the LLVM IR body for a single synthesized routine.
    /// Used by both GenerateSynthesizedRoutines (for non-generic types) and
    /// MonomorphizeGenericMethods (for monomorphized generic types).
    /// </summary>
    private void EmitSynthesizedRoutineBody(RoutineInfo routine, string funcName)
    {
        // Derived operators ($ne, $notcontains, $lt/$le/$gt/$ge) have real AST bodies
        // produced by the semantic analyzer. Emit them via the normal code path.
        if (_synthesizedBodies.TryGetValue(key: routine.RegistryKey, out Statement? astBody))
        {
            EmitSynthesizedBodyFromAst(routine: routine, funcName: funcName, body: astBody);
            return;
        }

        switch (routine.Name)
        {
            case "$eq":
                EmitSynthesizedEq(routine: routine, funcName: funcName);
                break;
            case "$cmp":
                EmitSynthesizedCmp(routine: routine, funcName: funcName);
                break;
            case "$hash":
                EmitSynthesizedHash(routine: routine, funcName: funcName);
                break;
            case "$create":
                if (routine.OwnerType?.Name == "Data")
                {
                    EmitSynthesizedDataCreate(routine: routine, funcName: funcName);
                }
                else if (routine.Parameters is [{ Type: FlagsTypeInfo or ChoiceTypeInfo }])
                {
                    // U64.$create(from: FlagsType) or S64.$create(from: ChoiceType)
                    EmitSynthesizedNumericCreate(routine: routine, funcName: funcName);
                }
                else
                {
                    EmitSynthesizedTextCreate(routine: routine, funcName: funcName);
                }

                break;
            case "$create!":
                EmitSynthesizedChoiceCreateFromText(routine: routine, funcName: funcName);
                break;
            case "$same":
                EmitSynthesizedSame(routine: routine, funcName: funcName);
                break;
            case "all_on":
                EmitSynthesizedAllOn(routine: routine, funcName: funcName);
                break;
            case "all_off":
                EmitSynthesizedAllOff(routine: routine, funcName: funcName);
                break;
            case "all_cases":
                EmitSynthesizedAllCases(routine: routine, funcName: funcName);
                break;
            // BuilderService complex per-type (list/struct returns — handled in codegen)
            case "member_variable_info":
                EmitSynthesizedMemberVariableInfo(routine: routine, funcName: funcName);
                break;
            case "all_member_variables":
                EmitSynthesizedAllFields(routine: routine, funcName: funcName);
                break;
            case "open_member_variables":
                EmitSynthesizedOpenFields(routine: routine, funcName: funcName);
                break;
            // BuilderService per-field lookup (runtime string compare — not expressible in plain RF AST)
            case "member_type_id":
                EmitSynthesizedMemberTypeId(routine: routine, funcName: funcName);
                break;
        }
    }

    /// <summary>
    /// Emits the body for a synthesized routine whose AST body was produced by the semantic
    /// analyzer (currently: $ne, $notcontains, $lt, $le, $gt, $ge).
    /// Uses the same function-header setup as GenerateFunctionDefinition but takes the body
    /// from the pre-built Statement rather than from a RoutineDeclaration.
    /// </summary>
    private void EmitSynthesizedBodyFromAst(RoutineInfo routine, string funcName, Statement body)
    {
        var paramList = new List<string>();
        if (routine.OwnerType != null)
        {
            string meType =
                GetImplicitMeParameterDeclaration(routine: routine, includeName: true);
            if (!meType.StartsWith(value: "void", comparisonType: StringComparison.Ordinal))
                paramList.Add(item: meType);
        }
        paramList.AddRange(collection:
            from param in routine.Parameters
            let paramType = GetParameterLLVMType(type: param.Type)
            select $"{paramType} %{param.Name}");

        string returnType = routine.ReturnType != null ? GetLLVMType(type: routine.ReturnType) : "void";
        string parameters = string.Join(separator: ", ", values: paramList);

        int savedLength = _functionDefinitions.Length;
        int savedTempCounter = _tempCounter;
        EmitLine(sb: _functionDefinitions, line: $"define {returnType} @{funcName}({parameters}) {{");
        EmitLine(sb: _functionDefinitions, line: "entry:");
        var bodyBuilder = new StringBuilder();
        try
        {
            GenerateFunctionBody(sb: bodyBuilder, body: body, routine: routine);
            _functionDefinitions.Append(value: _currentFunctionEntryAllocas);
            _functionDefinitions.Append(value: bodyBuilder);
        }
        catch
        {
            _functionDefinitions.Length = savedLength;
            _tempCounter = savedTempCounter;
            _generatedFunctionDefs.Remove(item: funcName);
            throw;
        }
        EmitLine(sb: _functionDefinitions, line: "}");
        EmitLine(sb: _functionDefinitions, line: "");
    }

    /// <summary>
    /// Emits the body for a synthesized $same routine: pointer identity comparison.
    /// </summary>
    private void EmitSynthesizedSame(RoutineInfo routine, string funcName)
    {
        if (routine.OwnerType == null)
        {
            return;
        }

        string meType = GetParameterLLVMType(type: routine.OwnerType);
        string youType = routine.Parameters.Count > 0
            ? GetParameterLLVMType(type: routine.Parameters[index: 0].Type)
            : meType;

        EmitLine(sb: _functionDefinitions,
            line: $"define i1 @{funcName}({meType} %me, {youType} %you) {{");
        EmitLine(sb: _functionDefinitions, line: "entry:");
        EmitLine(sb: _functionDefinitions, line: $"  %same = icmp eq {meType} %me, %you");
        EmitLine(sb: _functionDefinitions, line: "  ret i1 %same");
        EmitLine(sb: _functionDefinitions, line: "}");
        EmitLine(sb: _functionDefinitions, line: "");
    }


}
